import { beforeAll, afterEach, describe, it, expect, vi } from 'vitest';
import path from 'node:path';
import { readPack } from '../src/main/packs';
import { defaults, makeCatalog, groupSchema, guardTree, motionSchema, validateMotion, type Registry, type GroupInfo, type ActionNode, type Motion } from '../src/shared/schema';
import { ActionGroupRunner, frameIndex, type AnimationHost } from '../src/renderer/pet/engine';
import { candidates, weighted, NormalBehaviorDriver } from '../src/renderer/pet/behavior';
import { PetRuntime } from '../src/renderer/pet/PetRuntime';
import type { DesktopState } from '../src/shared/contracts';
import { clampRect, nearestArea, dimensions } from '../src/shared/geometry';
let registry: Registry;
beforeAll(async()=>{registry={revision:1,packs:[await readPack(path.resolve('resources/builtin'),true,p=>p)]};});
afterEach(()=>vi.useRealTimers());
const desktop:DesktopState={visible:true,dragging:false,pointerNear:false,position:{x:100,y:100},suspended:false};
function host(){const starts:string[]=[];const disposed:string[]=[];return {starts,disposed,begin:vi.fn((n:{type:string})=>{starts.push(n.type);return{update:vi.fn(),dispose:()=>disposed.push(n.type)};}),reset:vi.fn()} satisfies AnimationHost&{starts:string[];disposed:string[]};}
function runtime(){return new PetRuntime(structuredClone(registry),structuredClone(defaults),structuredClone(desktop),host());}
function group(timeline:ActionNode):GroupInfo { const catalog=makeCatalog(registry);return{...catalog.groups.values().next().value!,timeline,maxDurationMs:30000}; }
describe('schema and JSON extension',()=>{
  it('loads 13 distinct builtin groups and both motion formats',()=>{const c=makeCatalog(registry);expect(c.groups.size).toBe(13);expect(new Set([...c.groups.values()].map(g=>JSON.stringify(g.timeline))).size).toBe(13);expect([...c.motions.values()].some(m=>m.kind==='frame_animation')).toBe(true);});
  it('imports the supplied custom motion and group without changing TS',async()=>{const p=await readPack(path.resolve('examples/custom-action-pack'),false,p=>p);const r=runtime();r.replaceRegistry({revision:2,packs:[...registry.packs,p]});expect(r.port('manual').listCapabilities().find(g=>g.groupId==='user.celebrations:celebrate')?.available).toBe(true);expect(r.catalog.motions.has('user.celebrations:gentle_nod')).toBe(true);});
  it('rejects unknown fields and negative durations',()=>{const g=registry.packs[0].groups[0];expect(groupSchema.safeParse({...g,script:'evil'}).success).toBe(false);expect(groupSchema.safeParse({...g,timeline:{type:'wait',durationMs:-1}}).success).toBe(false);});
  it('rejects excessive depth before recursive schema parsing',()=>{let n:ActionNode={type:'wait',durationMs:1};for(let i=0;i<10;i++)n={type:'sequence',children:[n]};expect(()=>guardTree(n)).toThrow('深度');});
  it('rejects excessive node count',()=>{expect(()=>guardTree({children:Array.from({length:130},()=>({type:'wait'}))})).toThrow('128');});
  it('rejects an unknown motion and leaves previous registry intact',()=>{const r=runtime();const bad=structuredClone(registry);bad.packs[0].groups[0].timeline={type:'motion',motionId:'missing:bad',repeat:1};expect(()=>r.replaceRegistry(bad)).toThrow('未知 motion');expect(r.registry.revision).toBe(1);expect(r.catalog.groups.size).toBe(13);});
  it('rejects duplicate group IDs and channel conflicts',()=>{const bad=structuredClone(registry);bad.packs[0].groups.push(bad.packs[0].groups[0]);expect(()=>makeCatalog(bad)).toThrow('重复动作组');const conflict=structuredClone(registry);conflict.packs[0].groups[0].timeline={type:'parallel',children:[{type:'motion',motionId:'builtin.deepblue:wave',repeat:1},{type:'motion',motionId:'builtin.deepblue:sway',repeat:1}]};expect(()=>makeCatalog(conflict)).toThrow('通道冲突');});
  it('requires actual motion channels and increasing keyframes',()=>{const m=structuredClone(registry.packs[0].motions[0]);if(m.kind!=='rig_timeline')throw new Error();m.channels=['face'];expect(()=>validateMotion(m)).toThrow('通道');m.channels=['pose'];m.tracks[0].keyframes[1].timeMs=0;expect(()=>validateMotion(m)).toThrow('递增');});
  it('requires alpha limits, positive finite repeat and watchdog margin',()=>{const m=structuredClone(registry.packs[0].motions[0]);if(m.kind!=='rig_timeline')throw new Error();m.tracks[0].property='alpha';expect(()=>validateMotion(m)).toThrow('alpha');const g=registry.packs[0].groups[0];expect(groupSchema.safeParse({...g,timeline:{type:'motion',motionId:'builtin.deepblue:wave',repeat:Infinity}}).success).toBe(false);const bad=structuredClone(registry);bad.packs[0].groups[0].maxDurationMs=1;expect(()=>makeCatalog(bad)).toThrow('看门狗');});
  it('rejects frame ambiguity and missing assets',()=>{const m=structuredClone(registry.packs[0].motions.find(m=>m.kind==='frame_animation')!);if(m.kind!=='frame_animation')throw new Error();m.frameDurationsMs=[200,200,200,200];expect(()=>validateMotion(m)).toThrow('只能选择');const bad=structuredClone(registry);delete bad.packs[0].assets['assets/frame-0.png'];expect(()=>makeCatalog(bad)).toThrow('缺少图片');expect(motionSchema.safeParse({...m,frames:[]}).success).toBe(false);});
});
describe('timeline lifecycle',()=>{
  it('starts sequential leaves in order and releases before the next',()=>{const h=host(),done=vi.fn();const r=new ActionGroupRunner(group({type:'sequence',children:[{type:'bubble',text:'A',durationMs:100},{type:'bubble',text:'B',durationMs:100}]}),'x','manual',makeCatalog(registry),h,done);r.tick(0);expect(h.starts).toEqual(['bubble']);r.tick(100);expect(h.disposed).toEqual(['bubble']);expect(h.starts).toEqual(['bubble','bubble']);r.tick(100);expect(done).toHaveBeenCalledExactlyOnceWith('completed',undefined);});
  it('starts parallel leaves in same tick and waits for longest',()=>{const h=host(),done=vi.fn();const r=new ActionGroupRunner(group({type:'parallel',children:[{type:'bubble',text:'A',durationMs:100},{type:'wait',durationMs:300}]}),'x','manual',makeCatalog(registry),h,done);r.tick(0);expect(h.starts).toEqual(['bubble','wait']);r.tick(100);expect(done).not.toHaveBeenCalled();r.tick(200);expect(done).toHaveBeenCalledOnce();});
  it('recursively cancels active leaves and emits one terminal',()=>{const h=host(),done=vi.fn();const r=new ActionGroupRunner(group({type:'parallel',children:[{type:'bubble',text:'A',durationMs:1000},{type:'wait',durationMs:1000}]}),'x','manual',makeCatalog(registry),h,done);r.tick(0);r.cancel();r.cancel();r.tick(2000);expect(h.disposed).toHaveLength(2);expect(done).toHaveBeenCalledExactlyOnceWith('cancelled',undefined);});
  it('failure in one parallel branch releases its siblings',()=>{const h=host(),done=vi.fn();h.begin.mockImplementationOnce(()=>({update:vi.fn(),dispose:()=>h.disposed.push('first')})).mockImplementationOnce(()=>{throw new Error('broken');});const r=new ActionGroupRunner(group({type:'parallel',children:[{type:'wait',durationMs:100},{type:'bubble',text:'B',durationMs:100}]}),'x','manual',makeCatalog(registry),h,done);r.tick(0);expect(h.disposed).toEqual(['first']);expect(done).toHaveBeenCalledExactlyOnceWith('failed','broken');});
  it('watchdog cancels stuck work',()=>{const done=vi.fn();const g=group({type:'wait',durationMs:30000});g.maxDurationMs=100;const r=new ActionGroupRunner(g,'x','manual',makeCatalog(registry),host(),done);r.tick(101);expect(done).toHaveBeenCalledExactlyOnceWith('failed','ACTION_TIMEOUT');});
  it('frame sequence advances by milliseconds and clamps its final frame',()=>{const m=registry.packs[0].motions.find(m=>m.id==='frame_magic') as Extract<Motion,{kind:'frame_animation'}>;expect([0,199,200,600,800].map(t=>frameIndex(m,t))).toEqual([0,0,1,3,3]);});
});
describe('command gateway and priority',()=>{
  it('sleep only enters from standing and returns to standing on completion or cancellation',()=>{
    const h=host(),r=new PetRuntime(structuredClone(registry),structuredClone(defaults),structuredClone(desktop),h);
    expect(r.play('builtin.deepblue:greet_wave','normal').status).toBe('accepted');const previous=r.current;
    expect(r.play('builtin.deepblue:sleep_short','manual').errorCode).toBe('REQUIRES_STANDING');expect(r.current).toBe(previous);
    r.current!.cancel();h.disposed.length=0;expect(r.play('builtin.deepblue:sleep_short','manual').status).toBe('accepted');
    expect(r.current!.group.expectedDurationMs).toBe(14400);expect(r.current!.group.random.eligible).toBe(true);
    for(let i=0;i<144;i++)r.tick(100);expect(r.current).toBeNull();expect(h.reset).toHaveBeenCalled();
    expect(r.play('builtin.deepblue:sleep_short','system').status).toBe('accepted');r.setDesktop({...desktop,dragging:true});expect(r.current).toBeNull();
    expect(h.disposed.filter(x=>x==='motion')).toHaveLength(2);expect(h.disposed.filter(x=>x==='effect')).toHaveLength(2);
  });
  it('sleep layers are independently registered and missing tail assets are rejected',()=>{
    const m=makeCatalog(registry).motions.get('builtin.deepblue:sleep')!;expect(m.kind).toBe('frame_animation');
    if(m.kind==='frame_animation'){expect(m.layers?.[0].image).toBe('assets/sleep/tail.png');expect(m.frames).toHaveLength(96);expect(m.hitAreas).toHaveLength(2);}
    const bad=structuredClone(registry);delete bad.packs[0].assets['assets/sleep/tail.png'];expect(()=>makeCatalog(bad)).toThrow('缺少图片');
  });
  it('deduplicates identical command and rejects conflicting payload',async()=>{const r=runtime();const p=r.port('manual');const c={protocolVersion:1 as const,commandId:'same',type:'play_group' as const,groupId:'builtin.deepblue:greet_wave'};const a=await p.submit(c);expect(await p.submit(c)).toEqual(a);expect(r.events.filter(e=>e.type==='action_lifecycle')).toHaveLength(1);expect((await p.submit({...c,groupId:'builtin.deepblue:happy_hop'})).errorCode).toBe('COMMAND_ID_CONFLICT');});
  it('rejects expired, unknown, AI and forged source commands',()=>{const r=runtime();expect(r.submit({protocolVersion:1,commandId:'e',type:'play_group',groupId:'builtin.deepblue:greet_wave',expiresAtUnixMs:0},'manual').errorCode).toBe('COMMAND_EXPIRED');expect(r.play('no:such','manual').errorCode).toBe('UNKNOWN_GROUP');expect(r.play('builtin.deepblue:greet_wave','ai').errorCode).toBe('MODE_NOT_AVAILABLE');expect(r.submit({protocolVersion:1,commandId:'x',type:'stop_current',source:'system'},'manual').errorCode).toBe('INVALID_COMMAND');});
  it('interaction preempts random, manual preempts interaction, low priority is BUSY',()=>{const r=runtime();r.play('builtin.deepblue:greet_wave','normal');const old=r.current!;expect(r.play('builtin.deepblue:head_touch','interaction').status).toBe('accepted');expect(r.play('builtin.deepblue:look_around','normal').errorCode).toBe('BUSY');expect(r.play('builtin.deepblue:happy_hop','manual').status).toBe('accepted');const current=r.current;old.tick(10000);expect(r.current).toBe(current);expect(r.events.filter(e=>e.type==='action_lifecycle'&&e.payload.status==='cancelled')).toHaveLength(2);});
  it('drag cancels movement and locks manual preview',()=>{const r=runtime();r.play('builtin.deepblue:walk_left','normal');r.setDesktop({...desktop,dragging:true});expect(r.current).toBe(null);expect(r.play('builtin.deepblue:greet_wave','manual').errorCode).toBe('DRAG_LOCKED');r.setDesktop(desktop);expect(r.current?.group.id).toBe('drag_release');});
  it('fixed position rejects manual movement but roaming conditions do not',()=>{const r=runtime();r.settings.roaming=false;expect(r.play('builtin.deepblue:walk_left','manual').status).toBe('accepted');r.setSettings({...r.settings,fixedPosition:true});expect(r.current).toBeNull();expect(r.play('builtin.deepblue:walk_left','manual').errorCode).toBe('FIXED_POSITION');});
  it('disabled group cannot preview but random zero weight can',()=>{const r=runtime();r.settings.overrides['builtin.deepblue:greet_wave']={weight:0};expect(r.play('builtin.deepblue:greet_wave','manual').status).toBe('accepted');r.settings.overrides['builtin.deepblue:happy_hop']={enabled:false};expect(r.play('builtin.deepblue:happy_hop','manual').errorCode).toBe('GROUP_UNAVAILABLE');});
  it('AI mode check keeps active normal driver and action intact',async()=>{vi.useFakeTimers();const r=runtime();await r.start();r.play('builtin.deepblue:greet_wave','normal');const old=r.current;expect(r.setMode('ai').available).toBe(false);expect(r.driver.status).toBe('running');expect(r.current).toBe(old);await r.dispose();});
  it('valid registry replacement cancels old instance and updates revision',()=>{const r=runtime();r.play('builtin.deepblue:greet_wave','manual');r.replaceRegistry({...registry,revision:2});expect(r.current).toBeNull();expect(r.snapshot().registryRevision).toBe(2);});
  it('failed groups are isolated until successful registry replacement',()=>{const r=runtime();r.play('builtin.deepblue:greet_wave','manual');r.current!.fail('decode');expect(r.quarantined.has('builtin.deepblue:greet_wave')).toBe(true);expect(r.play('builtin.deepblue:greet_wave','manual').errorCode).toBe('GROUP_UNAVAILABLE');r.replaceRegistry({...registry,revision:2});expect(r.quarantined.size).toBe(0);});
  it('suspend-sized delta cancels movement rather than jumping time',()=>{const r=runtime();r.play('builtin.deepblue:walk_right','manual');r.tick(60000);expect(r.current).toBeNull();});
});
describe('normal random behavior',()=>{
  function state(){return{settings:structuredClone(defaults),lastInteraction:0,pointerNear:false,cooldowns:new Map<string,number>(),history:[] as string[],quarantined:new Set<string>()};}
  function pool(){return [...makeCatalog(registry).groups.values()];}
  it('weighted selection is deterministic and zero weights excluded',()=>{const gs=pool().slice(0,2).map((g,i)=>({...g,random:{...g.random,weight:i?3:1}}));expect(weighted(gs,()=>0)?.groupId).toBe(gs[0].groupId);expect(weighted(gs,()=>.26)?.groupId).toBe(gs[1].groupId);expect(weighted(gs.map(g=>({...g,random:{...g.random,weight:0}})),()=>0)).toBeUndefined();});
  it('applies cooldown, idle, pointer and roaming constraints',()=>{const s=state();s.settings.roaming=false;let gs=candidates(pool(),s,100000);expect(gs.some(g=>g.channels.includes('movement'))).toBe(false);s.settings.roaming=true;s.pointerNear=true;gs=candidates(pool(),s,100000);expect(gs.some(g=>g.conditions.requiresPointerAway)).toBe(false);s.cooldowns.set('builtin.deepblue:greet_wave',99000);expect(candidates(pool(),s,100000).some(g=>g.id==='greet_wave')).toBe(false);s.lastInteraction=99999;expect(candidates(pool(),s,100000)).toHaveLength(0);});
  it('history loosens oldest first and never bypasses cooldown',()=>{const gs=pool().filter(g=>['greet_wave','happy_hop'].includes(g.id));const s=state();s.history=gs.map(g=>g.groupId);expect(candidates(gs,s,100000).map(g=>g.groupId)).toEqual([gs[0].groupId]);s.cooldowns.set(gs[0].groupId,100000);s.cooldowns.set(gs[1].groupId,100000);expect(candidates(gs,s,100000)).toHaveLength(0);});
  it('single candidate can repeat when cooldown permits',()=>{const g=pool().find(g=>g.id==='greet_wave')!;const s=state();s.history=[g.groupId,g.groupId];expect(candidates([g],s,100000)).toHaveLength(1);});
  it('pause, stop and repeated resume have at most one timer',async()=>{vi.useFakeTimers();const r=runtime();await r.start();expect(vi.getTimerCount()).toBe(1);r.driver.pause();expect(vi.getTimerCount()).toBe(0);await vi.advanceTimersByTimeAsync(20000);expect(r.current).toBeNull();r.driver.resume();r.driver.resume();expect(vi.getTimerCount()).toBe(1);await r.dispose();expect(vi.getTimerCount()).toBe(0);});
  it('empty pool idles with bounded retry and never submits',async()=>{vi.useFakeTimers();const r=runtime();const submit=vi.fn(async()=>({commandId:'x',status:'rejected' as const}));const s=state();const driver=new NormalBehaviorDriver(()=>[],()=>s,()=>0);await driver.start({control:{...r.port('normal'),submit},subscribe:f=>r.subscribe(f)});await vi.advanceTimersByTimeAsync(20000);expect(submit).not.toHaveBeenCalled();expect(vi.getTimerCount()).toBe(1);await driver.stop();});
  it('cooldown begins on terminal event and only accepted start enters history',async()=>{vi.useFakeTimers();const r=runtime();await r.start();r.play('builtin.deepblue:greet_wave','normal');expect(r.driver.cooldowns.size).toBe(0);expect(r.driver.history).toEqual(['builtin.deepblue:greet_wave']);await vi.advanceTimersByTimeAsync(100);r.current!.cancel();expect(r.driver.cooldowns.get('builtin.deepblue:greet_wave')).toBe(Date.now());await r.dispose();});
});
describe('DIP geometry',()=>{
  it('clamps negative-coordinate display and nonzero work area origin',()=>{expect(clampRect({x:-3000,y:-100,width:340,height:420},{x:-1920,y:40,width:1920,height:1040})).toEqual({x:-1920,y:40,width:340,height:420});expect(clampRect({x:1900,y:1100,width:340,height:420},{x:100,y:40,width:1920,height:1040}).x).toBe(1680);});
  it('recovers removed display and handles different pet sizes',()=>{const area={x:0,y:0,width:1920,height:1040};expect(nearestArea({x:-1800,y:0,width:340,height:420},[area])).toBe(area);for(const size of [.6,1,1.5]){const d=dimensions(size);const r=clampRect({x:1920,y:1040,...d},area);expect(r.x+r.width).toBe(1920);expect(r.y+r.height).toBe(1040);}});
});

